/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Conexion;
import Modelo.InmuebleData;
import Modelo.Inquilino;
import Modelo.InquilinoData;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Merliques
 */
public class BuscarInquilinoVista extends javax.swing.JInternalFrame {
    
    DefaultTableModel modeloT= new DefaultTableModel();
    private InquilinoData inquilinoData;
    private Conexion conexion;
    private Inquilino inquilino;
   
    public BuscarInquilinoVista() {
        initComponents();
        
        jtInquilino.getTableHeader().setFont(new Font("Courier New",Font.BOLD,12));
        jtInquilino.getTableHeader().setOpaque(false);
        jtInquilino.getTableHeader().setBackground(new Color(32,136,203));
        jtInquilino.getTableHeader().setForeground(new Color(255,255,255));
        
        
        conexion=new Conexion();
        inquilinoData=new InquilinoData(conexion);
       
        modeloT.addColumn("Cuil Inquilino");
        modeloT.addColumn("Nombre");
        modeloT.addColumn("Apellido");
        modeloT.addColumn("Lugar de Trabajo");
        modeloT.addColumn("Nombre Garante");
        modeloT.addColumn("Dni Garante");
       
        //********** Array to JTable****
        
        //creamos el array
        String[] datoInquilino=new String[6];
        
        for(int i=0;i<inquilinoData.ObtenerInquilino().size();i++){
          
           datoInquilino[0]=(inquilinoData.ObtenerInquilino().get(i).getCuilInquilino());
           datoInquilino[1]=(inquilinoData.ObtenerInquilino().get(i).getNombre());
           datoInquilino[2]=(inquilinoData.ObtenerInquilino().get(i).getApellido());
           datoInquilino[3]=(inquilinoData.ObtenerInquilino().get(i).getLugarTrabajo());
           datoInquilino[4]=(inquilinoData.ObtenerInquilino().get(i).getNombreGarante());
           datoInquilino[5]=Integer.toString((inquilinoData.ObtenerInquilino().get(i).getDniGarante()));
           
            modeloT.addRow(datoInquilino);
        }
        
        jtInquilino.setModel(modeloT);
        
        //********** Array to JTable****
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtInquilino = new javax.swing.JTable();
        jbtnSeleccionar = new javax.swing.JButton();
        jtbCuilInquilinoBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbtnConsultar = new javax.swing.JButton();

        setClosable(true);

        jtInquilino.setBackground(new java.awt.Color(204, 255, 204));
        jtInquilino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtInquilino.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtInquilino);

        jbtnSeleccionar.setText("Seleccionar");
        jbtnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSeleccionarActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo");

        jbtnConsultar.setText("Consultar");
        jbtnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(533, 533, 533)
                                .addComponent(jbtnSeleccionar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jtbCuilInquilinoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 117, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtbCuilInquilinoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSeleccionarActionPerformed
        // TODO add your handling code here:
        
       int filaSelect=jtInquilino.getSelectedRow();
       
        String cuilIn=jtInquilino.getValueAt(filaSelect,0).toString();
           
        ContratoVistaN.jtbCuilInquilino.setText(cuilIn);
            
      this.dispose();
      
    }//GEN-LAST:event_jbtnSeleccionarActionPerformed

    private void jbtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConsultarActionPerformed
    
        
        
        String idUser=JOptionPane.showInputDialog ( "Introduzca un CUIL Inquilino :" );
            
            jtbCuilInquilinoBuscar.setText(idUser);
        
       // int id=Integer.parseInt(jtbCuit.getText());
            
                
                if(inquilino!=null){
                    modeloT.setRowCount(0);
                    jtbCuilInquilinoBuscar.setText((inquilino.getCuilInquilino()));
        
   
    }//GEN-LAST:event_jbtnConsultarActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnConsultar;
    private javax.swing.JButton jbtnSeleccionar;
    private javax.swing.JTable jtInquilino;
    private javax.swing.JTextField jtbCuilInquilinoBuscar;
    // End of variables declaration//GEN-END:variables
}
