/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Conexion;
import Modelo.InmuebleData;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Merliques
 */
public class BuscarInmuebleVista extends javax.swing.JInternalFrame {
    
    DefaultTableModel modeloT= new DefaultTableModel();
    private InmuebleData inmuebleData;
    private Conexion conexion;
   
    public BuscarInmuebleVista() {
        initComponents();
        
        
        jtInmuebles.getTableHeader().setFont(new Font("Courier New",Font.BOLD,12));
        jtInmuebles.getTableHeader().setOpaque(false);
        jtInmuebles.getTableHeader().setBackground(new Color(32,136,203));
        jtInmuebles.getTableHeader().setForeground(new Color(255,255,255));
        
        
        conexion=new Conexion();
        inmuebleData=new InmuebleData(conexion);
       
        modeloT.addColumn("Id Inmueble");
        modeloT.addColumn("CUIT Propietario");
        modeloT.addColumn("ID Tipo");
        modeloT.addColumn("Direccion");
        modeloT.addColumn("Altura");
        modeloT.addColumn("Superficie");
        modeloT.addColumn("Precio Base");
        modeloT.addColumn("Codigo Zona");
        modeloT.addColumn("Disponible");
       
       
        //********** Array to JTable****
        
        //creamos el array
        String[] datoInmueble=new String[9];
        
        for(int i=0;i<inmuebleData.buscarTodosInmuebles().size();i++){
          
           datoInmueble[0]=Integer.toString((inmuebleData.buscarTodosInmuebles().get(i).getIdInmueble()));
           datoInmueble[1]=(inmuebleData.buscarTodosInmuebles().get(i).getIdPropietario());
           datoInmueble[2]=Integer.toString((inmuebleData.buscarTodosInmuebles().get(i).getIdTipoInmueble()));
           datoInmueble[3]=(inmuebleData.buscarTodosInmuebles().get(i).getDireccion());
           datoInmueble[4]=Integer.toString((inmuebleData.buscarTodosInmuebles().get(i).getAlturaInmueble()));
           datoInmueble[5]=Double.toString((inmuebleData.buscarTodosInmuebles().get(i).getSuperficie()));
           datoInmueble[6]=Double.toString((inmuebleData.buscarTodosInmuebles().get(i).getPrecioBase()));
           datoInmueble[7]=Integer.toString((inmuebleData.buscarTodosInmuebles().get(i).getCodigoZona()));
           datoInmueble[8]=(inmuebleData.buscarTodosInmuebles().get(i).getDisponible());
           
            modeloT.addRow(datoInmueble);
        }
        
        jtInmuebles.setModel(modeloT);
        
        //********** Array to JTable****
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtInmuebles = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jtbTipo = new javax.swing.JTextField();
        jtbSuperficie = new javax.swing.JTextField();
        jtbPrecio = new javax.swing.JTextField();
        jtbZona = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbtnConsultar = new javax.swing.JButton();

        setClosable(true);

        jtInmuebles.setBackground(new java.awt.Color(204, 255, 204));
        jtInmuebles.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtInmuebles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtInmuebles);

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo");

        jLabel3.setText("Superficie");

        jLabel4.setText("Precio");

        jLabel5.setText("Zona");

        jbtnConsultar.setText("Consultar");
        jbtnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtbSuperficie, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtbPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jtbZona, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(533, 533, 533)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jbtnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbSuperficie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
       int filaSelect=jtInmuebles.getSelectedRow();
       
      
       String cuilIn=jtInmuebles.getValueAt(filaSelect,0).toString();
       String tipoIn=jtInmuebles.getValueAt(filaSelect,2).toString();
       String superficieIn=jtInmuebles.getValueAt(filaSelect,5).toString();
       String precioIn=jtInmuebles.getValueAt(filaSelect,6).toString();
       String zonaIn=jtInmuebles.getValueAt(filaSelect,7).toString();
       String estadoIn=jtInmuebles.getValueAt(filaSelect,7).toString();
      
      ContratoVistaN.jtbIdInmueble.setText(cuilIn);
      ContratoVistaN.jtbIdTipo.setText(tipoIn);
      ContratoVistaN.jtbSuperficie.setText(superficieIn);
      ContratoVistaN.jtbPrecio.setText(precioIn);
      ContratoVistaN.jtbCodigoZona.setText(zonaIn);
      ContratoVistaN.jtbEstado.setText(estadoIn);
      
      this.dispose();
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConsultarActionPerformed
           
        //********** Array to JTable****
      
    if (!jtbTipo.getText().isEmpty()&&!jtbZona.getText().isEmpty()&&!jtbSuperficie.getText().isEmpty()&&!jtbPrecio.getText().isEmpty())
    {
        modeloT.setRowCount(0);
             //creamos el array
        String[] datoInmueble=new String[9];      
        
            if( inmuebleData.buscarInmuebleContrato(Integer.parseInt(jtbTipo.getText()), Integer.parseInt(jtbZona.getText()),
                                                Double.parseDouble(jtbSuperficie.getText()),
                                                Double.parseDouble(jtbPrecio.getText())).size()>0){
        
                               for(int i=0;i<inmuebleData.buscarInmuebleContrato(Integer.parseInt(jtbTipo.getText()), Integer.parseInt(jtbZona.getText()),
                                                Double.parseDouble(jtbSuperficie.getText()),
                                                Double.parseDouble(jtbPrecio.getText())).size();i++){
                                   
                                                   datoInmueble[0]=Integer.toString((inmuebleData.buscarInmuebleContrato(Integer.parseInt(jtbTipo.getText()), Integer.parseInt(jtbZona.getText()),
                                                                                     Double.parseDouble(jtbSuperficie.getText()),
                                                                                     Double.parseDouble(jtbPrecio.getText())).get(i).getIdInmueble()));
                                                   datoInmueble[1]=(inmuebleData.buscarInmuebleContrato(Integer.parseInt(jtbTipo.getText()), Integer.parseInt(jtbZona.getText()),
                                                                                     Double.parseDouble(jtbSuperficie.getText()),
                                                                                     Double.parseDouble(jtbPrecio.getText())).get(i).getIdPropietario());
                                                    datoInmueble[2]=Integer.toString((inmuebleData.buscarInmuebleContrato(Integer.parseInt(jtbTipo.getText()), Integer.parseInt(jtbZona.getText()),
                                                                                     Double.parseDouble(jtbSuperficie.getText()),
                                                                                     Double.parseDouble(jtbPrecio.getText())).get(i).getIdTipoInmueble()));
                                                    datoInmueble[3]=(inmuebleData.buscarInmuebleContrato(Integer.parseInt(jtbTipo.getText()), Integer.parseInt(jtbZona.getText()),
                                                                                    Double.parseDouble(jtbSuperficie.getText()),
                                                                                    Double.parseDouble(jtbPrecio.getText())).get(i).getDireccion());
                                                    datoInmueble[4]=Integer.toString((inmuebleData.buscarInmuebleContrato(Integer.parseInt(jtbTipo.getText()), Integer.parseInt(jtbZona.getText()),
                                                                                    Double.parseDouble(jtbSuperficie.getText()),
                                                                                    Double.parseDouble(jtbPrecio.getText())).get(i).getAlturaInmueble()));
                                                    datoInmueble[5]=Double.toString((inmuebleData.buscarInmuebleContrato(Integer.parseInt(jtbTipo.getText()), Integer.parseInt(jtbZona.getText()),
                                                                                    Double.parseDouble(jtbSuperficie.getText()),
                                                                                    Double.parseDouble(jtbPrecio.getText())).get(i).getSuperficie()));
                                                    datoInmueble[6]=Double.toString((inmuebleData.buscarInmuebleContrato(Integer.parseInt(jtbTipo.getText()), Integer.parseInt(jtbZona.getText()),
                                                                                    Double.parseDouble(jtbSuperficie.getText()),
                                                                                    Double.parseDouble(jtbPrecio.getText())).get(i).getPrecioBase()));
                                                    datoInmueble[7]=Integer.toString((inmuebleData.buscarInmuebleContrato(Integer.parseInt(jtbTipo.getText()), Integer.parseInt(jtbZona.getText()),
                                                                                    Double.parseDouble(jtbSuperficie.getText()),
                                                                                    Double.parseDouble(jtbPrecio.getText())).get(i).getCodigoZona()));
                                                    datoInmueble[8]=(inmuebleData.buscarInmuebleContrato(Integer.parseInt(jtbTipo.getText()), Integer.parseInt(jtbZona.getText()),
                                                                                    Double.parseDouble(jtbSuperficie.getText()),
                                                                                    Double.parseDouble(jtbPrecio.getText())).get(i).getDisponible());
           
                                                    modeloT.addRow(datoInmueble);
            
                                                }
        
                    jtInmuebles.setModel(modeloT);
        
                    //********** Array to JTable****
            }else{
                             JOptionPane.showMessageDialog(null, "Lo siento, no disponemos de Inmueble con esas caracteristicas ..!", "Inmueble Inexistente", JOptionPane.WARNING_MESSAGE);
                                this.dispose();
                    }
    }else{
        
        JOptionPane.showMessageDialog(null, "Debe completar Todos loS Campos..!", "Consulta Incompleta", JOptionPane.WARNING_MESSAGE);
        
        } 
   
    }//GEN-LAST:event_jbtnConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnConsultar;
    private javax.swing.JTable jtInmuebles;
    private javax.swing.JTextField jtbPrecio;
    private javax.swing.JTextField jtbSuperficie;
    private javax.swing.JTextField jtbTipo;
    private javax.swing.JTextField jtbZona;
    // End of variables declaration//GEN-END:variables
}
