/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import Modelo.Conexion;
import Modelo.Contrato;
import Modelo.ContratoData;
import Modelo.Inmueble;
import Modelo.InmuebleData;
import Modelo.Inquilino;
import Modelo.InquilinoData;
import Modelo.Propietario;
import Modelo.PropietarioData;
import static Vista.MenuPrincipal.Escritorio;
import static Vista.MenuPrincipalN.jdEscritorio;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.Font;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Merliques
 */
public class ContratoVistaN extends javax.swing.JInternalFrame {

    /**
     * Creates new form PropietarioVista
     */
    private Conexion conexion;
    private Propietario propietario;
    private PropietarioData propietarioData;
    private Inquilino inquilino;
    private InquilinoData inquilinoData;
    private Contrato contrato;
    private ContratoData contratoData;
    private Inmueble inmueble;
    private InmuebleData inmuebleData;
    
    
        
    public ContratoVistaN() {
        initComponents();
        conexion=new Conexion();
        propietarioData=new PropietarioData(conexion);
        
        this.setSize(840, 449);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) 
      this.getUI()).setNorthPane(null);
        
        jtPropietario.getTableHeader().setFont(new Font("Courier New",Font.BOLD,12));
        jtPropietario.getTableHeader().setOpaque(false);
        jtPropietario.getTableHeader().setBackground(new Color(42, 62, 110));
        jtPropietario.getTableHeader().setForeground(new Color(255, 255, 255));
       
       
        
        //********** Array to JTable****
        
        DefaultTableModel modeloTabla=new DefaultTableModel();
        
        modeloTabla.addColumn("CUIT");
        modeloTabla.addColumn("Apellido");
        modeloTabla.addColumn("Nombres");
        modeloTabla.addColumn("Domicilio");
        modeloTabla.addColumn("Telefono");
        modeloTabla.addColumn("E-Mail");
        
        //creamos el array
        String[] datoPropietario=new String[6];
        
        for(int i=0;i<propietarioData.listarPropietario().size();i++){
          
           datoPropietario[0]=(propietarioData.listarPropietario().get(i).getCuitPropietario());
           datoPropietario[1]=(propietarioData.listarPropietario().get(i).getApellidoPropietario());
           datoPropietario[2]=(propietarioData.listarPropietario().get(i).getNombrePropietario());
           datoPropietario[3]=(propietarioData.listarPropietario().get(i).getDomicilioPropietario());
           datoPropietario[4]=(propietarioData.listarPropietario().get(i).getTelefono());
           datoPropietario[5]=(propietarioData.listarPropietario().get(i).getEmail());
           
            modeloTabla.addRow(datoPropietario);
        }
        
        jtPropietario.setModel(modeloTabla);
        
        //********** Array to JTable****
        
        
        //*iconos botones
        jlbtnGuardar.setEnabled(false);
        jlbtnActualizar.setEnabled(false);
        jlbtnBorrar.setEnabled(false);
        jlbtnNuevo.setEnabled(true);
        jlbtnBuscar.setEnabled(true);
        jlbtnCancelar.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPropietario = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jlbtnNuevo = new javax.swing.JLabel();
        jlbtnGuardar = new javax.swing.JLabel();
        jlbtnCancelar = new javax.swing.JLabel();
        jlbtnActualizar = new javax.swing.JLabel();
        jlbtnBorrar = new javax.swing.JLabel();
        jlbtnBuscar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jtbCuilInquilino = new javax.swing.JTextField();
        jtbIdInmueble = new javax.swing.JTextField();
        jtbIdTipo = new javax.swing.JTextField();
        jtbCodigoZona = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jdcInicio = new com.toedter.calendar.JDateChooser();
        jdcFinal = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jtbSuperficie = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtbPrecio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtbEstado = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jlblInicia = new javax.swing.JLabel();
        jlblFinaliza = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtPropietario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtPropietario.setEnabled(false);
        jScrollPane1.setViewportView(jtPropietario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 840, 200));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbtnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_add_file_32px.png"))); // NOI18N
        jlbtnNuevo.setToolTipText("Nuevo");
        jlbtnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbtnNuevoMousePressed(evt);
            }
        });
        jPanel1.add(jlbtnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 11, 54, 43));

        jlbtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_save_32px.png"))); // NOI18N
        jlbtnGuardar.setToolTipText("Guardar");
        jlbtnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbtnGuardarMousePressed(evt);
            }
        });
        jPanel1.add(jlbtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 11, 48, 43));

        jlbtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_undo_32px.png"))); // NOI18N
        jlbtnCancelar.setToolTipText("Cancelar");
        jlbtnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbtnCancelarMousePressed(evt);
            }
        });
        jPanel1.add(jlbtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 11, 47, 43));

        jlbtnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_refresh_32px.png"))); // NOI18N
        jlbtnActualizar.setToolTipText("Actualizar");
        jlbtnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbtnActualizarMousePressed(evt);
            }
        });
        jPanel1.add(jlbtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 11, 47, 43));

        jlbtnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_trash_can_32px.png"))); // NOI18N
        jlbtnBorrar.setToolTipText("Borrar");
        jlbtnBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbtnBorrarMousePressed(evt);
            }
        });
        jPanel1.add(jlbtnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 11, 70, 43));

        jlbtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_search_property_32px.png"))); // NOI18N
        jlbtnBuscar.setToolTipText("Buscar");
        jlbtnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbtnBuscarMousePressed(evt);
            }
        });
        jPanel1.add(jlbtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 11, 53, 43));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_close_window_32px_1.png"))); // NOI18N
        jLabel7.setToolTipText("Cerrar");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 30, 43));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 838, 70));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jtbCuilInquilino.setEditable(false);
        jtbCuilInquilino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtbCuilInquilino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtbCuilInquilinoKeyTyped(evt);
            }
        });

        jtbIdInmueble.setEditable(false);
        jtbIdInmueble.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtbIdTipo.setEditable(false);
        jtbIdTipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtbIdTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbIdTipoActionPerformed(evt);
            }
        });
        jtbIdTipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtbIdTipoKeyTyped(evt);
            }
        });

        jtbCodigoZona.setEditable(false);
        jtbCodigoZona.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("CUIL Inquilino");

        jLabel2.setText("Fecha Inicio");

        jLabel3.setText("Fecha Finaliza");

        jLabel4.setText("Id Inmueble");

        jLabel5.setText("Tipo");

        jLabel6.setText("Zona");

        jLabel8.setText("Superficie");

        jtbSuperficie.setEditable(false);
        jtbSuperficie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText("Precio");

        jtbPrecio.setEditable(false);
        jtbPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setText("Disponible");

        jtbEstado.setEditable(false);
        jtbEstado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("Buscar Inmueble");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar Inquilino");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jlblInicia.setText("inicia");

        jlblFinaliza.setText("finaliza");

        jButton3.setText("Mostrar Fechas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(98, 98, 98)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jtbIdInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jtbIdTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel6))
                                    .addComponent(jtbCodigoZona, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jdcInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblInicia))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jlblFinaliza)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jdcFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)
                                        .addComponent(jButton3)))
                                .addGap(67, 67, 67))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel8))
                                    .addComponent(jtbSuperficie, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel9))
                                    .addComponent(jtbPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jtbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtbCuilInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(471, 471, 471)))
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtbCuilInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtbIdInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtbIdTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtbCodigoZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtbSuperficie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtbPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jdcInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jdcFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblInicia)
                    .addComponent(jlblFinaliza))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 68, -1, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbIdTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbIdTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbIdTipoActionPerformed

    private void jtbCuilInquilinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbCuilInquilinoKeyTyped
        // TODO add your handling code here:
        
        char TestCaracter=evt.getKeyChar();
        if(!(Character.isDigit(TestCaracter)))
            evt.consume();
        
        if (jtbCuilInquilino.getText().length() >= 11) 
        evt.consume();
        
        
    }//GEN-LAST:event_jtbCuilInquilinoKeyTyped

    private void jtbIdTipoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbIdTipoKeyTyped
        // TODO add your handling code here:
         char TestCaracter=evt.getKeyChar();
        if(!(Character.isDigit(TestCaracter)))
            evt.consume();
        if (jtbIdTipo.getText().length() >= 16) 
        evt.consume();
    }//GEN-LAST:event_jtbIdTipoKeyTyped

    private void jlbtnNuevoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbtnNuevoMousePressed
        // TODO add your handling code here:
        jtbCuilInquilino.setText("");
        
        jtbIdInmueble.setText("");
        jtbIdTipo.setText("");
        jtbCodigoZona.setText("");
        
        jtbCuilInquilino.setEditable(true);
        
        jtbIdInmueble.setEditable(true);
        jtbIdTipo.setEditable(true);
        jtbCodigoZona.setEditable(true);
        
        jtbCuilInquilino.requestFocus();
        
        jlbtnGuardar.setEnabled(true);
        jlbtnActualizar.setEnabled(false);
        jlbtnBorrar.setEnabled(false);
        jlbtnNuevo.setEnabled(false);
        jlbtnBuscar.setEnabled(false);
        jlbtnCancelar.setEnabled(true);
        
        
        
    }//GEN-LAST:event_jlbtnNuevoMousePressed

    private void jlbtnGuardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbtnGuardarMousePressed
        // TODO add your handling code here:
        
    contrato=new Contrato();
    inquilino=new Inquilino();
    inmueble=new Inmueble();
    contratoData=new ContratoData(conexion);
    
      inquilino.setCuilInquilino((jtbCuilInquilino.getText()));
      inmueble.setIdInmueble(Integer.parseInt(jtbIdInmueble.getText()));
            //fechas San
            contrato.setFechaInicial(LocalDate.parse(getFecha(jdcInicio), DateTimeFormatter.ofPattern("dd-MM-yyyy")));
            contrato.setFechaFinal(LocalDate.parse(getFecha(jdcFinal), DateTimeFormatter.ofPattern("dd-MM-yyyy")));
            //
     
      contrato.setEstado("No");
      
      //
    // contrato.setFechaInicial(LocalDate.parse(getFecha(jdcFechaIni), DateTimeFormatter.ofPattern("dd-MM-yyyy")));
     //   contrato.setFechaFinal(LocalDate.parse(getFecha(jdcFechaFin), DateTimeFormatter.ofPattern("dd-MM-yyyy")));
      //  inquilino.setCuilInquilino(cbCodigoInquilino.getSelectedItem().toString());
      //  inmueble.setIdInmueble(Integer.parseInt(cbCodigoInmueble.getSelectedItem().toString()));
        contrato.setInquilino(inquilino);
        contrato.setInmueble(inmueble);
      //  contrato.setEstado(cbEstado.getSelectedItem().toString());
      //  contratoData.guardarContrato(contrato);
      
      //
      
      
      
      if((JOptionPane.showConfirmDialog(null, "Esta seguro que desea Guaradar el Propietario : "+jtbCuilInquilino.getText()+" ?", "Confirmar Guardado",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE))==0)
        {
            contratoData.guardarContrato(contrato);//llamamos al metodo guardar de la clase Data
        }
                 
      
        jtbCuilInquilino.setEditable(false);
        
        jtbIdInmueble.setEditable(false);
        jtbIdTipo.setEditable(false);
        jtbCodigoZona.setEditable(false);
      
        jlbtnNuevo.setEnabled(true);
        jlbtnGuardar.setEnabled(false);
        jlbtnBuscar.setEnabled(true);
      
        listarPropietarios();
        
        
    }//GEN-LAST:event_jlbtnGuardarMousePressed

    private void jlbtnCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbtnCancelarMousePressed
        // TODO add your handling code here:
        
        jtbCuilInquilino.setText("");
        
        jtbIdInmueble.setText("");
        jtbIdTipo.setText("");
        jtbCodigoZona.setText("");
        
        jtbCuilInquilino.setEditable(false);
        
        jtbIdInmueble.setEditable(false);
        jtbIdTipo.setEditable(false);
        jtbCodigoZona.setEditable(false);
        
                
        jtbCuilInquilino.requestFocus();
        
        jlbtnGuardar.setEnabled(false);
        jlbtnActualizar.setEnabled(false);
        jlbtnBorrar.setEnabled(false);
        jlbtnNuevo.setEnabled(true);
        jlbtnBuscar.setEnabled(true);
        jlbtnCancelar.setEnabled(false);
        
    }//GEN-LAST:event_jlbtnCancelarMousePressed

    private void jlbtnActualizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbtnActualizarMousePressed
        // TODO add your handling code here:
        
        if(jtbCuilInquilino.getText()!=null){
            
              propietario=new Propietario();
            
               
                propietario.setCuitPropietario((jtbCuilInquilino.getText()));
                
                propietario.setDomicilioPropietario(jtbIdInmueble.getText());
                propietario.setTelefono((jtbIdTipo.getText()));
                propietario.setEmail(jtbCodigoZona.getText());
                        
                propietarioData.actualizarPropietario(propietario);
                
                    jtbCuilInquilino.setEditable(false);
                    
                    jtbIdInmueble.setEditable(false);
                    jtbIdTipo.setEditable(false);
                    jtbCodigoZona.setEditable(false);
            
        }
                    jlbtnActualizar.setEnabled(false);
                    jlbtnBorrar.setEnabled(true);
                    jlbtnNuevo.setEnabled(true);
                    jlbtnCancelar.setEnabled(false);
                    
            listarPropietarios();
        
    }//GEN-LAST:event_jlbtnActualizarMousePressed

    private void jlbtnBorrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbtnBorrarMousePressed
        // TODO add your handling code here:
        
          
        String id=(jtbCuilInquilino.getText());
        
        
        
        if((JOptionPane.showConfirmDialog(null, "Realmente desea Eliminar el Propietario "+id+" ?", "Confirmar Borrado",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE))==0)
        {
           propietarioData.borrarPropietario(id); 
        }
                    jtbCuilInquilino.setEditable(false);
                    
                    jtbIdInmueble.setEditable(false);
                    jtbIdTipo.setEditable(false);
                    jtbCodigoZona.setEditable(false);
                    
                    jtbCuilInquilino.setText("");
                    
                    jtbIdInmueble.setText("");
                    jtbIdTipo.setText("");
                    jtbCodigoZona.setText("");
                    
        jlbtnBorrar.setEnabled(false);
        
        listarPropietarios();
    }//GEN-LAST:event_jlbtnBorrarMousePressed

    private void jlbtnBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbtnBuscarMousePressed
        // TODO add your handling code here:
        
         String idUser=JOptionPane.showInputDialog ( "Introduzca un CUIT :" );
            
            jtbCuilInquilino.setText(idUser);
        
       // int id=Integer.parseInt(jtbCuit.getText());
         
            propietario = propietarioData.buscarPropietario(idUser);
                
                if(propietario!=null){
                    
                    jtbCuilInquilino.setText((propietario.getCuitPropietario()));
                    
                    jtbIdInmueble.setText(propietario.getDomicilioPropietario());
                    jtbIdTipo.setText((propietario.getTelefono()));
                    jtbCodigoZona.setText(propietario.getEmail());
                    
                    jtbCuilInquilino.setEditable(true);
                    
                    jtbIdInmueble.setEditable(true);
                    jtbIdTipo.setEditable(true);
                    jtbCodigoZona.setEditable(true);
        
                    
                    jlbtnBorrar.setEnabled(true);
                    jlbtnActualizar.setEnabled(true);
                    jlbtnNuevo.setEnabled(false);
                    jlbtnCancelar.setEnabled(true);
                }
    }//GEN-LAST:event_jlbtnBuscarMousePressed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // TODO add your handling code here:
        MenuPrincipalN.jlblIcon.setVisible(true);
        MenuPrincipalN.jlblProp.setVisible(false);
        MenuPrincipalN.jlblInfo.setText("INFORMACION");
        this.dispose();
    }//GEN-LAST:event_jLabel7MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BuscarInmuebleVista buscarInmuebleVista=new BuscarInmuebleVista();

        buscarInmuebleVista.setVisible(true);
        jdEscritorio.add(buscarInmuebleVista);
        jdEscritorio.moveToFront(buscarInmuebleVista);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        BuscarInquilinoVista buscarInquilinoVista=new BuscarInquilinoVista();

        buscarInquilinoVista.setVisible(true);
        jdEscritorio.add(buscarInquilinoVista);
        jdEscritorio.moveToFront(buscarInquilinoVista);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       Date fechas= jdcInicio.getDate();
       long d=fechas.getTime();
       java.sql.Date fecha2=new java.sql.Date(d);
       JOptionPane.showMessageDialog(null,"Fecha : "+fecha2);
     jlblInicia.setText(LocalDate.parse(getFecha(jdcInicio), DateTimeFormatter.ofPattern("dd-MM-yyyy")).toString());
     jlblFinaliza.setText(LocalDate.parse(getFecha(jdcFinal), DateTimeFormatter.ofPattern("dd-MM-yyyy")).toString());
        
    }//GEN-LAST:event_jButton3ActionPerformed

    public void listarPropietarios(){
        
        //********** Array to JTable****
        
        DefaultTableModel modeloTabla=new DefaultTableModel();
        
        modeloTabla.addColumn("CUIT");
        modeloTabla.addColumn("Apellido");
        modeloTabla.addColumn("Nombres");
        modeloTabla.addColumn("Domicilio");
        modeloTabla.addColumn("Telefono");
        modeloTabla.addColumn("E-Mail");
        
        //creamos el array
        String[] datoPropietario=new String[6];
        
        for(int i=0;i<propietarioData.listarPropietario().size();i++){
          
           datoPropietario[0]=(propietarioData.listarPropietario().get(i).getCuitPropietario());
           datoPropietario[1]=(propietarioData.listarPropietario().get(i).getApellidoPropietario());
           datoPropietario[2]=(propietarioData.listarPropietario().get(i).getNombrePropietario());
           datoPropietario[3]=(propietarioData.listarPropietario().get(i).getDomicilioPropietario());
           datoPropietario[4]=(propietarioData.listarPropietario().get(i).getTelefono());
           datoPropietario[5]=(propietarioData.listarPropietario().get(i).getEmail());
           
            modeloTabla.addRow(datoPropietario);
        }
        
        jtPropietario.setModel(modeloTabla);
        
        //********** Array to JTable****
        
    }
    
    //metodo San para fechas
    
    public String getFecha(JDateChooser jdc){
        SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
        if(jdc.getDate() != null){
            return formato.format(jdc.getDate());
        }else{
            return null;
        }
    }
    
    //metodo merliques
    
    public java.sql.Date fechaM(JDateChooser jdc){
        Date fechas= jdc.getDate();
       long d=fechas.getTime();
       java.sql.Date fecha2=new java.sql.Date(d);
       JOptionPane.showMessageDialog(null,"Fecha : "+fecha2);
       return fecha2;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcFinal;
    private com.toedter.calendar.JDateChooser jdcInicio;
    private javax.swing.JLabel jlblFinaliza;
    private javax.swing.JLabel jlblInicia;
    private javax.swing.JLabel jlbtnActualizar;
    private javax.swing.JLabel jlbtnBorrar;
    private javax.swing.JLabel jlbtnBuscar;
    private javax.swing.JLabel jlbtnCancelar;
    private javax.swing.JLabel jlbtnGuardar;
    private javax.swing.JLabel jlbtnNuevo;
    private javax.swing.JTable jtPropietario;
    public static javax.swing.JTextField jtbCodigoZona;
    public static javax.swing.JTextField jtbCuilInquilino;
    public static javax.swing.JTextField jtbEstado;
    public static javax.swing.JTextField jtbIdInmueble;
    public static javax.swing.JTextField jtbIdTipo;
    public static javax.swing.JTextField jtbPrecio;
    public static javax.swing.JTextField jtbSuperficie;
    // End of variables declaration//GEN-END:variables
}
