/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Inquilino;
import Modelo.InquilinoData;
import java.util.List;

/**
 *
 * @author Ferna
 */
public class InquilinoVista extends javax.swing.JInternalFrame {

    /**
     * Creates new form InquilinoVista
     */
    public InquilinoVista() {
        initComponents();
        
        setTitle("Vista Inquilino");
        setSize(800,600);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        lblApellido = new javax.swing.JLabel();
        lblLugarGarante = new javax.swing.JLabel();
        lblNombreGarante = new javax.swing.JLabel();
        lblDniGarante = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCuilInquilino = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tbApellido = new javax.swing.JTextField();
        tbLugarTrabajo = new javax.swing.JTextField();
        tbNombreGarante = new javax.swing.JTextField();
        tbDniGarante = new javax.swing.JTextField();
        tbNombre = new javax.swing.JTextField();
        tbCuilInquilino = new javax.swing.JTextField();
        pnlFondoBotones = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dgvDatos = new javax.swing.JTable();

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setPreferredSize(new java.awt.Dimension(800, 600));

        pnlFondo.setBackground(new java.awt.Color(51, 51, 51));

        lblApellido.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(255, 255, 255));
        lblApellido.setText("Apellido");

        lblLugarGarante.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLugarGarante.setForeground(new java.awt.Color(255, 255, 255));
        lblLugarGarante.setText("Lugar de Trabajo");

        lblNombreGarante.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNombreGarante.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreGarante.setText("Nombre Del Garante");

        lblDniGarante.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDniGarante.setForeground(new java.awt.Color(255, 255, 255));
        lblDniGarante.setText("Dni Del Garante");

        lblNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre");

        lblCuilInquilino.setBackground(new java.awt.Color(255, 255, 255));
        lblCuilInquilino.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCuilInquilino.setForeground(new java.awt.Color(255, 255, 255));
        lblCuilInquilino.setText("Cuil Inquilino");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Datos de Inquilino");

        tbApellido.setBackground(new java.awt.Color(0, 0, 51));
        tbApellido.setForeground(new java.awt.Color(255, 255, 255));
        tbApellido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbApellidoKeyTyped(evt);
            }
        });

        tbLugarTrabajo.setBackground(new java.awt.Color(0, 0, 51));
        tbLugarTrabajo.setForeground(new java.awt.Color(255, 255, 255));
        tbLugarTrabajo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbLugarTrabajo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbLugarTrabajoKeyTyped(evt);
            }
        });

        tbNombreGarante.setBackground(new java.awt.Color(0, 0, 51));
        tbNombreGarante.setForeground(new java.awt.Color(255, 255, 255));
        tbNombreGarante.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbNombreGarante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbNombreGaranteKeyTyped(evt);
            }
        });

        tbDniGarante.setBackground(new java.awt.Color(0, 0, 51));
        tbDniGarante.setForeground(new java.awt.Color(255, 255, 255));
        tbDniGarante.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbDniGarante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbDniGaranteKeyTyped(evt);
            }
        });

        tbNombre.setBackground(new java.awt.Color(0, 0, 51));
        tbNombre.setForeground(new java.awt.Color(255, 255, 255));
        tbNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbNombreKeyTyped(evt);
            }
        });

        tbCuilInquilino.setBackground(new java.awt.Color(0, 0, 51));
        tbCuilInquilino.setForeground(new java.awt.Color(255, 255, 255));
        tbCuilInquilino.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbCuilInquilino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbCuilInquilinoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(lblNombreGarante)
                    .addComponent(lblLugarGarante)
                    .addComponent(lblApellido)
                    .addComponent(lblDniGarante)
                    .addComponent(lblCuilInquilino))
                .addGap(45, 45, 45)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tbNombreGarante, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(tbLugarTrabajo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbApellido, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbNombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbDniGarante)
                    .addComponent(tbCuilInquilino))
                .addGap(0, 36, Short.MAX_VALUE))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuilInquilino)
                    .addComponent(tbCuilInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addGap(18, 18, 18)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellido))
                .addGap(18, 18, 18)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbLugarTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLugarGarante))
                .addGap(18, 18, 18)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbNombreGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreGarante))
                .addGap(18, 18, 18)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbDniGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDniGarante))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnlFondoBotones.setBackground(new java.awt.Color(51, 51, 51));

        btnEliminar.setBackground(new java.awt.Color(102, 102, 102));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/basura.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(102, 102, 102));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(102, 102, 102));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/investigacion.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(102, 102, 102));
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/refrescar.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFondoBotonesLayout = new javax.swing.GroupLayout(pnlFondoBotones);
        pnlFondoBotones.setLayout(pnlFondoBotonesLayout);
        pnlFondoBotonesLayout.setHorizontalGroup(
            pnlFondoBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFondoBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlFondoBotonesLayout.setVerticalGroup(
            pnlFondoBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoBotonesLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnGuardar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        dgvDatos.setBackground(new java.awt.Color(0, 0, 51));
        dgvDatos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dgvDatos.setForeground(new java.awt.Color(255, 255, 255));
        dgvDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cuil ", "Nombre", "Apellido", "Lugar de Trabajo", "Nombre de Garante", "Dni de Garante"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(dgvDatos);
        dgvDatos.getAccessibleContext().setAccessibleParent(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlFondoBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlFondoBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        InquilinoData inquilinoData = new InquilinoData();
        inquilinoData.Eliminar(Integer.parseInt(tbCuilInquilino.getText()) );

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Inquilino inquilino = new Inquilino();
        inquilino.setCuilInquilino(Integer.parseInt(tbCuilInquilino.getText()));
        inquilino.setNombre(tbNombre.getText());
        inquilino.setApellido(tbApellido.getText());
        inquilino.setLugarTrabajo(tbLugarTrabajo.getText());
        inquilino.setNombreGarante(tbNombreGarante.getText());
        inquilino.setDniGarante(Integer.parseInt(tbDniGarante.getText()));

        InquilinoData inquilinoData = new InquilinoData();

        inquilinoData.Guardar(inquilino);

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        InquilinoData inquilinoData = new InquilinoData();
        Inquilino inquilino;

        inquilino= inquilinoData.Buscar(Integer.parseInt(tbCuilInquilino.getText()));
        tbCuilInquilino.setText(inquilino.getCuilInquilino()+"");
        tbNombre.setText(inquilino.getNombre());
        tbApellido.setText(inquilino.getApellido());
        tbLugarTrabajo.setText(inquilino.getLugarTrabajo());
        tbNombreGarante.setText(inquilino.getNombreGarante());
        tbDniGarante.setText(inquilino.getDniGarante()+"");

        inquilino.setCuilInquilino(Integer.parseInt(tbCuilInquilino.getText()));
        inquilino.setNombre(tbNombre.getText());
        inquilino.setApellido(tbApellido.getText());
        inquilino.setLugarTrabajo(tbLugarTrabajo.getText());
        inquilino.setNombreGarante(tbNombreGarante.getText());
        inquilino.setDniGarante(Integer.parseInt(tbDniGarante.getText()));

        inquilinoData.Modificar(inquilino);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        InquilinoData inquilinoData = new InquilinoData();
        Inquilino inquilino;

        inquilino= inquilinoData.Buscar(Integer.parseInt(tbCuilInquilino.getText()));
        tbCuilInquilino.setText(inquilino.getCuilInquilino()+"");
        tbNombre.setText(inquilino.getNombre());
        tbApellido.setText(inquilino.getApellido());
        tbLugarTrabajo.setText(inquilino.getLugarTrabajo());
        tbNombreGarante.setText(inquilino.getNombreGarante());
        tbDniGarante.setText(inquilino.getDniGarante()+"");

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tbCuilInquilinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbCuilInquilinoKeyTyped
        char tecla = evt.getKeyChar();
        if(tecla < '0' || tecla >'9')
        {
            evt.consume();
        }
        
        if(tbCuilInquilino.getText().length() >= 11)
        {
            evt.consume();
        }
    }//GEN-LAST:event_tbCuilInquilinoKeyTyped

    private void tbNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbNombreKeyTyped
        char tecla = evt.getKeyChar();
        if(!Character.isAlphabetic(tecla))
        {
            evt.consume();
        }
        if(tbNombre.getText().length() >= 20)
        {
            evt.consume();
        }
    }//GEN-LAST:event_tbNombreKeyTyped

    private void tbApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbApellidoKeyTyped
        char tecla = evt.getKeyChar();
        if(!Character.isAlphabetic(tecla))
        {
            evt.consume();
        }
        if(tbApellido.getText().length() >= 20)
        {
            evt.consume();
        }
    }//GEN-LAST:event_tbApellidoKeyTyped

    private void tbLugarTrabajoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbLugarTrabajoKeyTyped
        char tecla = evt.getKeyChar();
        if(!Character.isAlphabetic(tecla))
        {
            evt.consume();
        }
        if(tbLugarTrabajo.getText().length() >= 50)
        {
            evt.consume();
        }
    }//GEN-LAST:event_tbLugarTrabajoKeyTyped

    private void tbNombreGaranteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbNombreGaranteKeyTyped
        char tecla = evt.getKeyChar();
        if(!Character.isAlphabetic(tecla))
        {
            evt.consume();
        }
        if(tbNombreGarante.getText().length() >= 20)
        {
            evt.consume();
        }
    }//GEN-LAST:event_tbNombreGaranteKeyTyped

    private void tbDniGaranteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbDniGaranteKeyTyped
        char tecla = evt.getKeyChar();
        if(tecla < '0' || tecla >'9')
        {
            evt.consume();
        }
        if(tbDniGarante.getText().length() >= 8)
        {
            evt.consume();
        }
    }//GEN-LAST:event_tbDniGaranteKeyTyped

    public void CargarTabla()
    {
        InquilinoData inquilino = new InquilinoData();
        List<Inquilino> lista = inquilino.Obtener();
        
        for(Inquilino items:lista)
        {
            
        }
        
        
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTable dgvDatos;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCuilInquilino;
    private javax.swing.JLabel lblDniGarante;
    private javax.swing.JLabel lblLugarGarante;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreGarante;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlFondoBotones;
    private javax.swing.JTextField tbApellido;
    private javax.swing.JTextField tbCuilInquilino;
    private javax.swing.JTextField tbDniGarante;
    private javax.swing.JTextField tbLugarTrabajo;
    private javax.swing.JTextField tbNombre;
    private javax.swing.JTextField tbNombreGarante;
    // End of variables declaration//GEN-END:variables
}
