/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ferna
 */
public class InquilinoVista extends javax.swing.JInternalFrame {

    
    private Inquilino inquilino;
    private InquilinoData inquilinoData;
    
    
    /**
     * Creates new form InquilinoVista
     */
    public InquilinoVista() {
        initComponents();
        
        this.setSize(840, 449);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) 
        this.getUI()).setNorthPane(null);
        
        
        //*iconos botones
        jlbtnGuardar.setEnabled(false);
        jlbtnActualizar.setEnabled(false);
        jlbtnBorrar.setEnabled(false);
        jlbtnNuevo.setEnabled(true);
        jlbtnBuscar.setEnabled(true);
        jlbtnCancelar.setEnabled(false);
        
        
        
        Tabla();
        MostrarTabla();    
    }
       
    
    Conexion con=new Conexion();
    DefaultTableModel modelo = new DefaultTableModel();
    List<Inquilino> lista = new ArrayList<Inquilino>();
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dgvDatos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tdatos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jlbtnNuevo = new javax.swing.JLabel();
        jlbtnGuardar = new javax.swing.JLabel();
        jlbtnCancelar = new javax.swing.JLabel();
        jlbtnActualizar = new javax.swing.JLabel();
        jlbtnBorrar = new javax.swing.JLabel();
        jlbtnBuscar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblCuilInquilino = new javax.swing.JLabel();
        tbCuilInquilino = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        tbNombre = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        tbApellido = new javax.swing.JTextField();
        lblLugarGarante = new javax.swing.JLabel();
        tbLugarTrabajo = new javax.swing.JTextField();
        lblNombreGarante = new javax.swing.JLabel();
        tbNombreGarante = new javax.swing.JTextField();
        lblDniGarante = new javax.swing.JLabel();
        tbDniGarante = new javax.swing.JTextField();

        dgvDatos.setBackground(new java.awt.Color(0, 0, 51));
        dgvDatos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dgvDatos.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(dgvDatos);

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tdatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Tdatos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 838, 180));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbtnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_add_file_32px.png"))); // NOI18N
        jlbtnNuevo.setToolTipText("Nuevo");
        jlbtnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbtnNuevoMousePressed(evt);
            }
        });
        jPanel1.add(jlbtnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 11, 54, 43));

        jlbtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_save_32px.png"))); // NOI18N
        jlbtnGuardar.setToolTipText("Guardar");
        jlbtnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbtnGuardarMousePressed(evt);
            }
        });
        jPanel1.add(jlbtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 11, 48, 43));

        jlbtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_undo_32px.png"))); // NOI18N
        jlbtnCancelar.setToolTipText("Cancelar");
        jlbtnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbtnCancelarMousePressed(evt);
            }
        });
        jPanel1.add(jlbtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 11, 47, 43));

        jlbtnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_refresh_32px.png"))); // NOI18N
        jlbtnActualizar.setToolTipText("Actualizar");
        jlbtnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbtnActualizarMousePressed(evt);
            }
        });
        jPanel1.add(jlbtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 11, 47, 43));

        jlbtnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_trash_can_32px.png"))); // NOI18N
        jlbtnBorrar.setToolTipText("Borrar");
        jlbtnBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbtnBorrarMousePressed(evt);
            }
        });
        jPanel1.add(jlbtnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 11, 70, 43));

        jlbtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_search_property_32px.png"))); // NOI18N
        jlbtnBuscar.setToolTipText("Buscar");
        jlbtnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbtnBuscarMousePressed(evt);
            }
        });
        jPanel1.add(jlbtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 11, 53, 43));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_close_window_32px_1.png"))); // NOI18N
        jLabel7.setToolTipText("Cerrar");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 30, 43));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 70));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCuilInquilino.setBackground(new java.awt.Color(255, 255, 255));
        lblCuilInquilino.setText("Cuil Inquilino");
        jPanel2.add(lblCuilInquilino, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        tbCuilInquilino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbCuilInquilino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbCuilInquilinoKeyTyped(evt);
            }
        });
        jPanel2.add(tbCuilInquilino, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 140, 21));

        lblNombre.setText("Nombre");
        jPanel2.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        tbNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbNombreKeyTyped(evt);
            }
        });
        jPanel2.add(tbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 231, 21));

        lblApellido.setText("Apellido");
        jPanel2.add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        tbApellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbApellidoKeyTyped(evt);
            }
        });
        jPanel2.add(tbApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 245, 20));

        lblLugarGarante.setText("Lugar de Trabajo");
        jPanel2.add(lblLugarGarante, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        tbLugarTrabajo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbLugarTrabajo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbLugarTrabajoKeyTyped(evt);
            }
        });
        jPanel2.add(tbLugarTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 180, 20));

        lblNombreGarante.setText("Nombre Del Garante");
        jPanel2.add(lblNombreGarante, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        tbNombreGarante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbNombreGarante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbNombreGaranteKeyTyped(evt);
            }
        });
        jPanel2.add(tbNombreGarante, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 245, 20));

        lblDniGarante.setText("Dni Del Garante");
        jPanel2.add(lblDniGarante, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, 23));

        tbDniGarante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbDniGarante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbDniGaranteKeyTyped(evt);
            }
        });
        jPanel2.add(tbDniGarante, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 210, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 840, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void MostrarTabla()
    {
        InquilinoData inquilinoData = new InquilinoData(con);    
        
        lista = inquilinoData.ObtenerInquilino();
        
        BorrarFilas();
        
        for(Inquilino item:lista)
        {
            modelo.addRow(new Object[]{item.getCuilInquilino(),item.getNombre(),item.getApellido(),item.getLugarTrabajo(),item.getNombreGarante(),item.getDniGarante() });
        }
        
    }
       
    public void Tabla()
    {
        List<Object> columns = new ArrayList<Object>();
        columns.add("Cuil");
        columns.add("Nombre");
        columns.add("Apellido");
        columns.add("Lugar De Trabajo");
        columns.add("Nombre De Garante");
        columns.add("Dni De Garante");
        
        for(Object item:columns)
        {
            modelo.addColumn(item);
        }
        
        Tdatos.setModel(modelo);
        
    }
    
    public void BorrarFilas()
    {
        for(int a = modelo.getRowCount()-1;a>= 0;a--)
        {
            modelo.removeRow(a);
        }
    }
    
    
    
    private void tbCuilInquilinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbCuilInquilinoKeyTyped
        char tecla = evt.getKeyChar();
        if(tecla < '0' || tecla >'9')
        {
            evt.consume();
        }
        
        if(tbCuilInquilino.getText().length() >= 11)
        {
            evt.consume();
        }
    }//GEN-LAST:event_tbCuilInquilinoKeyTyped

    private void tbNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbNombreKeyTyped
        char tecla = evt.getKeyChar();
        if(!Character.isAlphabetic(tecla) && !Character.isWhitespace(tecla))
        {
            evt.consume();
        }
        if(tbNombre.getText().length() >= 20)
        {
            evt.consume();
        }
    }//GEN-LAST:event_tbNombreKeyTyped

    private void tbApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbApellidoKeyTyped
        char tecla = evt.getKeyChar();
        if(!Character.isAlphabetic(tecla) && !Character.isWhitespace(tecla))
        {
            evt.consume();
        }
        if(tbApellido.getText().length() >= 20)
        {
            evt.consume();
        }
    }//GEN-LAST:event_tbApellidoKeyTyped

    private void tbLugarTrabajoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbLugarTrabajoKeyTyped

        if(tbLugarTrabajo.getText().length() >= 50)
        {
            evt.consume();
        }
    }//GEN-LAST:event_tbLugarTrabajoKeyTyped

    private void tbNombreGaranteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbNombreGaranteKeyTyped
        char tecla = evt.getKeyChar();
        if(!Character.isAlphabetic(tecla) && !Character.isWhitespace(tecla))
        {
            evt.consume();
        }
        if(tbNombreGarante.getText().length() >= 20)
        {
            evt.consume();
        }
    }//GEN-LAST:event_tbNombreGaranteKeyTyped

    private void tbDniGaranteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbDniGaranteKeyTyped
        char tecla = evt.getKeyChar();
        if(tecla < '0' || tecla >'9')
        {
            evt.consume();
        }
        if(tbDniGarante.getText().length() >= 8)
        {
            evt.consume();
        }
    }//GEN-LAST:event_tbDniGaranteKeyTyped
       
    private void jlbtnNuevoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbtnNuevoMousePressed
        // TODO add your handling code here:
        tbCuilInquilino.setText("");
        tbApellido.setText("");
        tbNombre.setText("");
        tbLugarTrabajo.setText("");
        tbNombreGarante.setText("");
        tbDniGarante.setText("");

        tbCuilInquilino.setEditable(true);
        tbApellido.setEditable(true);
        tbNombre.setEditable(true);
        tbLugarTrabajo.setEditable(true);
        tbNombreGarante.setEditable(true);
        tbDniGarante.setEditable(true);

        tbCuilInquilino.requestFocus();

        jlbtnGuardar.setEnabled(true);
        jlbtnActualizar.setEnabled(false);
        jlbtnBorrar.setEnabled(false);
        jlbtnNuevo.setEnabled(false);
        jlbtnBuscar.setEnabled(false);
        jlbtnCancelar.setEnabled(true);

    }//GEN-LAST:event_jlbtnNuevoMousePressed

    private void jlbtnGuardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbtnGuardarMousePressed
        // TODO add your handling code here:

       inquilino=new Inquilino();
       inquilinoData=new InquilinoData(con);

        inquilino.setCuilInquilino((tbCuilInquilino.getText()));
        inquilino.setApellido(tbApellido.getText());
        inquilino.setNombre(tbNombre.getText());
        inquilino.setLugarTrabajo(tbLugarTrabajo.getText());
        inquilino.setNombreGarante((tbNombreGarante.getText()));
        inquilino.setDniGarante(Integer.parseInt(tbDniGarante.getText()));

        if((JOptionPane.showConfirmDialog(null, "Esta seguro que desea Guaradar el Inquilino : "+tbCuilInquilino.getText()+" ?", "Confirmar Guardado",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE))==0)
{
    inquilinoData.GuardarInquilino(inquilino);//llamamos al metodo guardar de la clase Data
    }

    tbCuilInquilino.setEditable(false);
    tbApellido.setEditable(false);
    tbNombre.setEditable(false);
    tbLugarTrabajo.setEditable(false);
    tbNombreGarante.setEditable(false);
    tbDniGarante.setEditable(false);

    jlbtnNuevo.setEnabled(true);
    jlbtnGuardar.setEnabled(false);
    jlbtnBuscar.setEnabled(true);

    MostrarTabla();

    }//GEN-LAST:event_jlbtnGuardarMousePressed

    private void jlbtnCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbtnCancelarMousePressed
        // TODO add your handling code here:

        tbCuilInquilino.setText("");
        tbApellido.setText("");
        tbNombre.setText("");
        tbLugarTrabajo.setText("");
        tbNombreGarante.setText("");
        tbDniGarante.setText("");

        tbCuilInquilino.setEditable(false);
        tbApellido.setEditable(false);
        tbNombre.setEditable(false);
        tbLugarTrabajo.setEditable(false);
        tbNombreGarante.setEditable(false);
        tbDniGarante.setEditable(false);

        tbCuilInquilino.requestFocus();

        jlbtnGuardar.setEnabled(false);
        jlbtnActualizar.setEnabled(false);
        jlbtnBorrar.setEnabled(false);
        jlbtnNuevo.setEnabled(true);
        jlbtnBuscar.setEnabled(true);
        jlbtnCancelar.setEnabled(false);

    }//GEN-LAST:event_jlbtnCancelarMousePressed

    private void jlbtnActualizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbtnActualizarMousePressed
        // TODO add your handling code here:

        if(tbCuilInquilino.getText()!=null){

       inquilino=new Inquilino();
       inquilinoData=new InquilinoData(con);

            inquilino.setCuilInquilino((tbCuilInquilino.getText()));
            inquilino.setApellido(tbApellido.getText());
            inquilino.setNombre(tbNombre.getText());
            inquilino.setLugarTrabajo(tbLugarTrabajo.getText());
            inquilino.setNombreGarante((tbNombreGarante.getText()));
            inquilino.setDniGarante(Integer.parseInt(tbDniGarante.getText()));

            inquilinoData.ModificarInquilino(inquilino);

            tbCuilInquilino.setEditable(false);
            tbApellido.setEditable(false);
            tbNombre.setEditable(false);
            tbLugarTrabajo.setEditable(false);
            tbNombreGarante.setEditable(false);
            tbDniGarante.setEditable(false);

        }
        jlbtnActualizar.setEnabled(false);
        jlbtnBorrar.setEnabled(true);
        jlbtnNuevo.setEnabled(true);
        jlbtnCancelar.setEnabled(false);

        MostrarTabla();

    }//GEN-LAST:event_jlbtnActualizarMousePressed

    private void jlbtnBorrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbtnBorrarMousePressed
        // TODO add your handling code here:

        String id=(tbCuilInquilino.getText());

        if((JOptionPane.showConfirmDialog(null, "Realmente desea Eliminar el Inquilino "+id+" ?", "Confirmar Borrado",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE))==0)
{
    inquilinoData.EliminarInquilino(id);
    }
            tbCuilInquilino.setEditable(false);
            tbApellido.setEditable(false);
            tbNombre.setEditable(false);
            tbLugarTrabajo.setEditable(false);
            tbNombreGarante.setEditable(false);
            tbDniGarante.setEditable(false);

            tbCuilInquilino.setText("");
             tbApellido.setText("");
            tbNombre.setText("");
            tbLugarTrabajo.setText("");
            tbNombreGarante.setText("");
            tbDniGarante.setText("");

            jlbtnBorrar.setEnabled(false);

            MostrarTabla();
    }//GEN-LAST:event_jlbtnBorrarMousePressed

    private void jlbtnBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbtnBuscarMousePressed
        // TODO add your handling code here:

        String idUser=JOptionPane.showInputDialog ( "Introduzca un CUIL :" );

        tbCuilInquilino.setText(idUser);

        // int id=Integer.parseInt(jtbCuit.getText());
        inquilino=new Inquilino();
        inquilinoData=new InquilinoData(con);

        inquilino = inquilinoData.BuscarInquilino(idUser);
        

        if(inquilino!=null){

            tbCuilInquilino.setText((inquilino.getCuilInquilino()));
            tbApellido.setText(inquilino.getApellido());
            tbNombre.setText(inquilino.getNombre());
            tbLugarTrabajo.setText(inquilino.getLugarTrabajo());
            tbNombreGarante.setText((inquilino.getNombreGarante()));
            tbDniGarante.setText(Integer.toString(inquilino.getDniGarante()));

            tbCuilInquilino.setEditable(false);
            tbApellido.setEditable(false);
            tbNombre.setEditable(false);
            tbLugarTrabajo.setEditable(false);
            tbNombreGarante.setEditable(false);
            tbDniGarante.setEditable(false);
            

            jlbtnBorrar.setEnabled(true);
            jlbtnActualizar.setEnabled(true);
            jlbtnNuevo.setEnabled(false);
            jlbtnCancelar.setEnabled(true);
        }
    }//GEN-LAST:event_jlbtnBuscarMousePressed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // TODO add your handling code here:
        MenuPrincipalN.jlblIcon.setVisible(true);
        MenuPrincipalN.jlblInq.setVisible(false);
        MenuPrincipalN.jlblInfo.setText("INFORMACION");
        this.dispose();
    }//GEN-LAST:event_jLabel7MousePressed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tdatos;
    private javax.swing.JTable dgvDatos;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlbtnActualizar;
    private javax.swing.JLabel jlbtnBorrar;
    private javax.swing.JLabel jlbtnBuscar;
    private javax.swing.JLabel jlbtnCancelar;
    private javax.swing.JLabel jlbtnGuardar;
    private javax.swing.JLabel jlbtnNuevo;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCuilInquilino;
    private javax.swing.JLabel lblDniGarante;
    private javax.swing.JLabel lblLugarGarante;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreGarante;
    private javax.swing.JTextField tbApellido;
    private javax.swing.JTextField tbCuilInquilino;
    private javax.swing.JTextField tbDniGarante;
    private javax.swing.JTextField tbLugarTrabajo;
    private javax.swing.JTextField tbNombre;
    private javax.swing.JTextField tbNombreGarante;
    // End of variables declaration//GEN-END:variables
}
