/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;

import javax.swing.JPanel;

/**
 *
 * @author Merliques
 */
public class MenuPrincipalN extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipalN() {
        initComponents();
         this.setSize(1060, 600);
         this.setLocationRelativeTo(null);
            jlblIn.setVisible(false);
            jlblProp.setVisible(false);
            jlblInq.setVisible(false);
            jlblCon.setVisible(false);
            jlblIcon.setVisible(true);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFondo = new javax.swing.JPanel();
        jpIzq = new javax.swing.JPanel();
        btnInquilinos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnInmuebles = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnPropietarios = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnContratos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jlblInfo = new javax.swing.JLabel();
        jlblIcon = new javax.swing.JLabel();
        jlblIn = new javax.swing.JLabel();
        jlblProp = new javax.swing.JLabel();
        jlblInq = new javax.swing.JLabel();
        jlblCon = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jdEscritorio = new javax.swing.JDesktopPane();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setLocationByPlatform(true);
        setName("frmMenu"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        jpFondo.setBackground(new java.awt.Color(255, 255, 255));
        jpFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpIzq.setBackground(new java.awt.Color(64, 43, 100));
        jpIzq.setForeground(new java.awt.Color(255, 255, 255));
        jpIzq.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInquilinos.setBackground(new java.awt.Color(64, 43, 100));
        btnInquilinos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInquilinosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInquilinosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInquilinosMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_father_32px_1.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INQUILINOS");

        javax.swing.GroupLayout btnInquilinosLayout = new javax.swing.GroupLayout(btnInquilinos);
        btnInquilinos.setLayout(btnInquilinosLayout);
        btnInquilinosLayout.setHorizontalGroup(
            btnInquilinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnInquilinosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        btnInquilinosLayout.setVerticalGroup(
            btnInquilinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnInquilinosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnInquilinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addGroup(btnInquilinosLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jpIzq.add(btnInquilinos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 220, 60));

        btnInmuebles.setBackground(new java.awt.Color(64, 43, 100));
        btnInmuebles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInmueblesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInmueblesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInmueblesMousePressed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_exterior_32px_1.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("INMUEBLES");

        javax.swing.GroupLayout btnInmueblesLayout = new javax.swing.GroupLayout(btnInmuebles);
        btnInmuebles.setLayout(btnInmueblesLayout);
        btnInmueblesLayout.setHorizontalGroup(
            btnInmueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnInmueblesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
        btnInmueblesLayout.setVerticalGroup(
            btnInmueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnInmueblesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnInmueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnInmueblesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );

        jpIzq.add(btnInmuebles, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 220, 60));

        btnPropietarios.setBackground(new java.awt.Color(64, 43, 100));
        btnPropietarios.setPreferredSize(new java.awt.Dimension(176, 60));
        btnPropietarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPropietariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPropietariosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPropietariosMousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_landlord_32px_2.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PROPIETARIOS");

        javax.swing.GroupLayout btnPropietariosLayout = new javax.swing.GroupLayout(btnPropietarios);
        btnPropietarios.setLayout(btnPropietariosLayout);
        btnPropietariosLayout.setHorizontalGroup(
            btnPropietariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPropietariosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
        btnPropietariosLayout.setVerticalGroup(
            btnPropietariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPropietariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnPropietariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPropietariosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );

        jpIzq.add(btnPropietarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 220, 60));

        btnContratos.setBackground(new java.awt.Color(64, 43, 100));
        btnContratos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnContratosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnContratosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnContratosMousePressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_purchase_order_32px.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CONTRATOS");

        javax.swing.GroupLayout btnContratosLayout = new javax.swing.GroupLayout(btnContratos);
        btnContratos.setLayout(btnContratosLayout);
        btnContratosLayout.setHorizontalGroup(
            btnContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnContratosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        btnContratosLayout.setVerticalGroup(
            btnContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnContratosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addGroup(btnContratosLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jpIzq.add(btnContratos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 220, 60));
        jpIzq.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 190, 20));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo-ulp4.png"))); // NOI18N
        jpIzq.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MENÚ");
        jpIzq.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 90, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_menu_32px.png"))); // NOI18N
        jpIzq.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 40, 30));
        jpIzq.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 190, 20));

        jpFondo.add(jpIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 600));

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblInfo.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jlblInfo.setForeground(new java.awt.Color(255, 255, 255));
        jlblInfo.setText("INFORMACIÓN");
        jPanel1.add(jlblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 210, 30));

        jlblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_info_32px.png"))); // NOI18N
        jPanel1.add(jlblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 40, 50));

        jlblIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_exterior_32px_1.png"))); // NOI18N
        jPanel1.add(jlblIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 45, -1));

        jlblProp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_landlord_32px_2.png"))); // NOI18N
        jPanel1.add(jlblProp, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, -1));

        jlblInq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_father_32px_1.png"))); // NOI18N
        jPanel1.add(jlblInq, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, -1));

        jlblCon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_purchase_order_32px.png"))); // NOI18N
        jPanel1.add(jlblCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("TUDS");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 153, 153));
        jLabel18.setText("Laboratorio I");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel16.setBackground(new java.awt.Color(204, 204, 204));
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("DANIEL    GONZALES");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        jLabel17.setBackground(new java.awt.Color(204, 204, 204));
        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setText("FERNANDO  NOVARA");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, -1, -1));

        jLabel15.setBackground(new java.awt.Color(204, 204, 204));
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("NORBERTO VALDEÓN");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("GRUPO 9");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jpFondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 840, 80));

        jdEscritorio.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jdEscritorioLayout = new javax.swing.GroupLayout(jdEscritorio);
        jdEscritorio.setLayout(jdEscritorioLayout);
        jdEscritorioLayout.setHorizontalGroup(
            jdEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        jdEscritorioLayout.setVerticalGroup(
            jdEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jpFondo.add(jdEscritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 840, 450));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_close_window_32px_2.png"))); // NOI18N
        jLabel9.setToolTipText("Salir");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jpFondo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("INMOBILIARIA");
        jpFondo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void btnInmueblesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInmueblesMousePressed
        // TODO add your handling code here:
       
        setColor(btnInmuebles);
        reSetColor(btnPropietarios);
        reSetColor(btnInquilinos);
        reSetColor(btnContratos);
        
        jdEscritorio.removeAll();
        jdEscritorio.repaint();
        
        InmuebleVistanN inmueble=new InmuebleVistanN();
            inmueble.setVisible(true);
            jdEscritorio.add(inmueble);
            jdEscritorio.moveToFront(inmueble);
            jlblInfo.setText("INMUEBLES");
           
            jlblIn.setVisible(true);
            jlblProp.setVisible(false);
            jlblInq.setVisible(false);
            jlblCon.setVisible(false);
            jlblIcon.setVisible(false);
        
        
    }//GEN-LAST:event_btnInmueblesMousePressed

    private void btnPropietariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPropietariosMousePressed
        // TODO add your handling code here:
        reSetColor(btnInmuebles);
        setColor(btnPropietarios);
        reSetColor(btnInquilinos);
        reSetColor(btnContratos);
        
            jdEscritorio.removeAll();
            jdEscritorio.repaint();
        
        PropietarioVista propietario=new PropietarioVista();
            propietario.setVisible(true);
            jdEscritorio.add(propietario);
            jdEscritorio.moveToFront(propietario);
            jlblInfo.setText("PROPIETARIOS");
           
            jlblIn.setVisible(false);
            jlblProp.setVisible(true);
            jlblInq.setVisible(false);
            jlblCon.setVisible(false);
            jlblIcon.setVisible(false);
        
        
    }//GEN-LAST:event_btnPropietariosMousePressed

    private void btnInquilinosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInquilinosMousePressed
        // TODO add your handling code here:
        reSetColor(btnInmuebles);
        reSetColor(btnPropietarios);
        setColor(btnInquilinos);
        reSetColor(btnContratos);
        
            jdEscritorio.removeAll();
            jdEscritorio.repaint();
        
            InquilinoVista inquilino=new InquilinoVista();
            inquilino.setVisible(true);
            jdEscritorio.add(inquilino);
            jdEscritorio.moveToFront(inquilino);
            jlblInfo.setText("INQUILINOS");
            
            jlblIn.setVisible(false);
            jlblProp.setVisible(false);
            jlblInq.setVisible(true);
            jlblCon.setVisible(false);
            jlblIcon.setVisible(false);
    }//GEN-LAST:event_btnInquilinosMousePressed

    private void btnContratosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContratosMousePressed
        // TODO add your handling code here:
        reSetColor(btnInmuebles);
        reSetColor(btnPropietarios);
        reSetColor(btnInquilinos);
        setColor(btnContratos);
        
        jdEscritorio.removeAll();
            jdEscritorio.repaint();
        
            ContratoVistaN contrato=new ContratoVistaN();
            contrato.setVisible(true);
            jdEscritorio.add(contrato);
            jdEscritorio.moveToFront(contrato);
        jlblInfo.setText("CONTRATOS");
        
            jlblIn.setVisible(false);
            jlblProp.setVisible(false);
            jlblInq.setVisible(false);
            jlblCon.setVisible(true);
            jlblIcon.setVisible(false);
    }//GEN-LAST:event_btnContratosMousePressed

    private void btnInmueblesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInmueblesMouseEntered
        // TODO add your handling code here:
        setColor(btnInmuebles);
        reSetColor(btnPropietarios);
        reSetColor(btnInquilinos);
        reSetColor(btnContratos);
    }//GEN-LAST:event_btnInmueblesMouseEntered

    private void btnInmueblesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInmueblesMouseExited
        // TODO add your handling code here:
        reSetColor(btnInmuebles);
        reSetColor(btnPropietarios);
        reSetColor(btnInquilinos);
        reSetColor(btnContratos);
    }//GEN-LAST:event_btnInmueblesMouseExited

    private void btnPropietariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPropietariosMouseEntered
        // TODO add your handling code here:
        reSetColor(btnInmuebles);
        setColor(btnPropietarios);
        reSetColor(btnInquilinos);
        reSetColor(btnContratos);
    }//GEN-LAST:event_btnPropietariosMouseEntered

    private void btnPropietariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPropietariosMouseExited
        // TODO add your handling code here:
        reSetColor(btnInmuebles);
        reSetColor(btnPropietarios);
        reSetColor(btnInquilinos);
        reSetColor(btnContratos);
    }//GEN-LAST:event_btnPropietariosMouseExited

    private void btnInquilinosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInquilinosMouseEntered
        // TODO add your handling code here:
        reSetColor(btnInmuebles);
        reSetColor(btnPropietarios);
        setColor(btnInquilinos);
        reSetColor(btnContratos);
    }//GEN-LAST:event_btnInquilinosMouseEntered

    private void btnInquilinosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInquilinosMouseExited
        // TODO add your handling code here:
        reSetColor(btnInmuebles);
        reSetColor(btnPropietarios);
        reSetColor(btnInquilinos);
        reSetColor(btnContratos);
    }//GEN-LAST:event_btnInquilinosMouseExited

    private void btnContratosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContratosMouseEntered
        // TODO add your handling code here:
        reSetColor(btnInmuebles);
        reSetColor(btnPropietarios);
        reSetColor(btnInquilinos);
        setColor(btnContratos);
    }//GEN-LAST:event_btnContratosMouseEntered

    private void btnContratosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContratosMouseExited
        // TODO add your handling code here:
        reSetColor(btnInmuebles);
        reSetColor(btnPropietarios);
        reSetColor(btnInquilinos);
        reSetColor(btnContratos);
    }//GEN-LAST:event_btnContratosMouseExited

    /**
     * @param args the command line arguments
     */
    
    void setColor(JPanel jPanel){
     jPanel.setBackground(new Color(85,65,118));
    }
    
    void reSetColor(JPanel jPanel){
     jPanel.setBackground(new Color(64,43,100));
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnContratos;
    private javax.swing.JPanel btnInmuebles;
    private javax.swing.JPanel btnInquilinos;
    private javax.swing.JPanel btnPropietarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public static javax.swing.JDesktopPane jdEscritorio;
    public static javax.swing.JLabel jlblCon;
    public static javax.swing.JLabel jlblIcon;
    public static javax.swing.JLabel jlblIn;
    public static javax.swing.JLabel jlblInfo;
    public static javax.swing.JLabel jlblInq;
    public static javax.swing.JLabel jlblProp;
    private javax.swing.JPanel jpFondo;
    private javax.swing.JPanel jpIzq;
    // End of variables declaration//GEN-END:variables
}
