/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import Modelo.Conexion;
import Modelo.Propietario;
import Modelo.PropietarioData;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Merliques
 */
public class PropietarioVista extends javax.swing.JInternalFrame {

    /**
     * Creates new form PropietarioVista
     */
    private Conexion conexion;
    private Propietario propietario;
    private PropietarioData propietarioData;
    
    
        
    public PropietarioVista() {
        initComponents();
        conexion=new Conexion();
        propietarioData=new PropietarioData(conexion);
        
        this.setSize(840, 449);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) 
      this.getUI()).setNorthPane(null);
        
        jtPropietario.getTableHeader().setFont(new Font("Courier New",Font.BOLD,12));
        jtPropietario.getTableHeader().setOpaque(false);
        jtPropietario.getTableHeader().setBackground(new Color(42, 62, 110));
        jtPropietario.getTableHeader().setForeground(new Color(255, 255, 255));
       
       
        
        //********** Array to JTable****
        
        DefaultTableModel modeloTabla=new DefaultTableModel();
        
        modeloTabla.addColumn("CUIT");
        modeloTabla.addColumn("Apellido");
        modeloTabla.addColumn("Nombres");
        modeloTabla.addColumn("Domicilio");
        modeloTabla.addColumn("Telefono");
        modeloTabla.addColumn("E-Mail");
        
        //creamos el array
        String[] datoPropietario=new String[6];
        
        for(int i=0;i<propietarioData.listarPropietario().size();i++){
          
           datoPropietario[0]=(propietarioData.listarPropietario().get(i).getCuitPropietario());
           datoPropietario[1]=(propietarioData.listarPropietario().get(i).getApellidoPropietario());
           datoPropietario[2]=(propietarioData.listarPropietario().get(i).getNombrePropietario());
           datoPropietario[3]=(propietarioData.listarPropietario().get(i).getDomicilioPropietario());
           datoPropietario[4]=(propietarioData.listarPropietario().get(i).getTelefono());
           datoPropietario[5]=(propietarioData.listarPropietario().get(i).getEmail());
           
            modeloTabla.addRow(datoPropietario);
        }
        
        jtPropietario.setModel(modeloTabla);
        
        //********** Array to JTable****
        
        
        //*iconos botones
        jlbtnGuardar.setEnabled(false);
        jlbtnActualizar.setEnabled(false);
        jlbtnBorrar.setEnabled(false);
        jlbtnNuevo.setEnabled(true);
        jlbtnBuscar.setEnabled(true);
        jlbtnCancelar.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPropietario = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jlbtnNuevo = new javax.swing.JLabel();
        jlbtnGuardar = new javax.swing.JLabel();
        jlbtnCancelar = new javax.swing.JLabel();
        jlbtnActualizar = new javax.swing.JLabel();
        jlbtnBorrar = new javax.swing.JLabel();
        jlbtnBuscar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jtbCuit = new javax.swing.JTextField();
        jtbApellido = new javax.swing.JTextField();
        jtbNombre = new javax.swing.JTextField();
        jtbDomicilio = new javax.swing.JTextField();
        jtbTelefono = new javax.swing.JTextField();
        jtbCorreo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtPropietario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtPropietario.setEnabled(false);
        jScrollPane1.setViewportView(jtPropietario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 840, 200));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbtnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_add_file_32px.png"))); // NOI18N
        jlbtnNuevo.setToolTipText("Nuevo");
        jlbtnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbtnNuevoMousePressed(evt);
            }
        });
        jPanel1.add(jlbtnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 11, 54, 43));

        jlbtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_save_32px.png"))); // NOI18N
        jlbtnGuardar.setToolTipText("Guardar");
        jlbtnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbtnGuardarMousePressed(evt);
            }
        });
        jPanel1.add(jlbtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 11, 48, 43));

        jlbtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_undo_32px.png"))); // NOI18N
        jlbtnCancelar.setToolTipText("Cancelar");
        jlbtnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbtnCancelarMousePressed(evt);
            }
        });
        jPanel1.add(jlbtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 11, 47, 43));

        jlbtnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_refresh_32px.png"))); // NOI18N
        jlbtnActualizar.setToolTipText("Actualizar");
        jlbtnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbtnActualizarMousePressed(evt);
            }
        });
        jPanel1.add(jlbtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 11, 47, 43));

        jlbtnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_trash_can_32px.png"))); // NOI18N
        jlbtnBorrar.setToolTipText("Borrar");
        jlbtnBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbtnBorrarMousePressed(evt);
            }
        });
        jPanel1.add(jlbtnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 11, 70, 43));

        jlbtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_search_property_32px.png"))); // NOI18N
        jlbtnBuscar.setToolTipText("Buscar");
        jlbtnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbtnBuscarMousePressed(evt);
            }
        });
        jPanel1.add(jlbtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 11, 53, 43));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8_close_window_32px_1.png"))); // NOI18N
        jLabel7.setToolTipText("Cerrar");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 30, 43));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 838, 70));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jtbCuit.setEditable(false);
        jtbCuit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtbCuit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtbCuitKeyTyped(evt);
            }
        });

        jtbApellido.setEditable(false);
        jtbApellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtbApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtbApellidoKeyTyped(evt);
            }
        });

        jtbNombre.setEditable(false);
        jtbNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtbNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtbNombreKeyTyped(evt);
            }
        });

        jtbDomicilio.setEditable(false);
        jtbDomicilio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtbTelefono.setEditable(false);
        jtbTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtbTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbTelefonoActionPerformed(evt);
            }
        });
        jtbTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtbTelefonoKeyTyped(evt);
            }
        });

        jtbCorreo.setEditable(false);
        jtbCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("CUIT Propietario");

        jLabel2.setText("Apellido");

        jLabel3.setText("Nombres");

        jLabel4.setText("Domicilio");

        jLabel5.setText("Teléfono");

        jLabel6.setText("e-mail");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtbCuit, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtbApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jtbDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(106, 106, 106)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtbTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtbCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(77, 77, 77))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtbCuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtbDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 68, -1, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbTelefonoActionPerformed

    private void jtbCuitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbCuitKeyTyped
        // TODO add your handling code here:
        
        char TestCaracter=evt.getKeyChar();
        if(!(Character.isDigit(TestCaracter)))
            evt.consume();
        
        if (jtbCuit.getText().length() >= 11) 
        evt.consume();
        
        
    }//GEN-LAST:event_jtbCuitKeyTyped

    private void jtbTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbTelefonoKeyTyped
        // TODO add your handling code here:
         char TestCaracter=evt.getKeyChar();
        if(!(Character.isDigit(TestCaracter)))
            evt.consume();
        if (jtbTelefono.getText().length() >= 16) 
        evt.consume();
    }//GEN-LAST:event_jtbTelefonoKeyTyped

    private void jtbApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbApellidoKeyTyped
        // TODO add your handling code here:
         char TestCaracter=evt.getKeyChar();
        if(!(Character.isAlphabetic(TestCaracter))&& !(Character.isWhitespace(TestCaracter)))
            evt.consume();
    }//GEN-LAST:event_jtbApellidoKeyTyped

    private void jtbNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbNombreKeyTyped
        // TODO add your handling code here:
         char TestCaracter=evt.getKeyChar();
        if(!(Character.isAlphabetic(TestCaracter))&& !(Character.isWhitespace(TestCaracter)))
            evt.consume();
        
    }//GEN-LAST:event_jtbNombreKeyTyped

    private void jlbtnNuevoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbtnNuevoMousePressed
        // TODO add your handling code here:
        jtbCuit.setText("");
        jtbApellido.setText("");
        jtbNombre.setText("");
        jtbDomicilio.setText("");
        jtbTelefono.setText("");
        jtbCorreo.setText("");
        
        jtbCuit.setEditable(true);
        jtbApellido.setEditable(true);
        jtbNombre.setEditable(true);
        jtbDomicilio.setEditable(true);
        jtbTelefono.setEditable(true);
        jtbCorreo.setEditable(true);
        
        jtbCuit.requestFocus();
        
        jlbtnGuardar.setEnabled(true);
        jlbtnActualizar.setEnabled(false);
        jlbtnBorrar.setEnabled(false);
        jlbtnNuevo.setEnabled(false);
        jlbtnBuscar.setEnabled(false);
        jlbtnCancelar.setEnabled(true);
        
        
        
    }//GEN-LAST:event_jlbtnNuevoMousePressed

    private void jlbtnGuardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbtnGuardarMousePressed
        // TODO add your handling code here:
        
        propietario=new Propietario();
     
      
      propietario.setCuitPropietario((jtbCuit.getText()));
      propietario.setApellidoPropietario(jtbApellido.getText());
      propietario.setNombrePropietario(jtbNombre.getText());
      propietario.setDomicilioPropietario(jtbDomicilio.getText());
      propietario.setTelefono((jtbTelefono.getText()));
      propietario.setEmail(jtbCorreo.getText());
      
      
      if((JOptionPane.showConfirmDialog(null, "Esta seguro que desea Guaradar el Propietario : "+jtbCuit.getText()+" ?", "Confirmar Guardado",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE))==0)
        {
            propietarioData.guardarPropietario(propietario);//llamamos al metodo guardar de la clase Data
        }
                 
      
        jtbCuit.setEditable(false);
        jtbApellido.setEditable(false);
        jtbNombre.setEditable(false);
        jtbDomicilio.setEditable(false);
        jtbTelefono.setEditable(false);
        jtbCorreo.setEditable(false);
      
        jlbtnNuevo.setEnabled(true);
        jlbtnGuardar.setEnabled(false);
        jlbtnBuscar.setEnabled(true);
      
        listarPropietarios();
        
        
    }//GEN-LAST:event_jlbtnGuardarMousePressed

    private void jlbtnCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbtnCancelarMousePressed
        // TODO add your handling code here:
        
        jtbCuit.setText("");
        jtbApellido.setText("");
        jtbNombre.setText("");
        jtbDomicilio.setText("");
        jtbTelefono.setText("");
        jtbCorreo.setText("");
        
        jtbCuit.setEditable(false);
        jtbApellido.setEditable(false);
        jtbNombre.setEditable(false);
        jtbDomicilio.setEditable(false);
        jtbTelefono.setEditable(false);
        jtbCorreo.setEditable(false);
        
                
        jtbCuit.requestFocus();
        
        jlbtnGuardar.setEnabled(false);
        jlbtnActualizar.setEnabled(false);
        jlbtnBorrar.setEnabled(false);
        jlbtnNuevo.setEnabled(true);
        jlbtnBuscar.setEnabled(true);
        jlbtnCancelar.setEnabled(false);
        
    }//GEN-LAST:event_jlbtnCancelarMousePressed

    private void jlbtnActualizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbtnActualizarMousePressed
        // TODO add your handling code here:
        
        if(jtbCuit.getText()!=null){
            
              propietario=new Propietario();
            
               
                propietario.setCuitPropietario((jtbCuit.getText()));
                propietario.setApellidoPropietario(jtbApellido.getText());
                propietario.setNombrePropietario(jtbNombre.getText());
                propietario.setDomicilioPropietario(jtbDomicilio.getText());
                propietario.setTelefono((jtbTelefono.getText()));
                propietario.setEmail(jtbCorreo.getText());
                        
                propietarioData.actualizarPropietario(propietario);
                
                    jtbCuit.setEditable(false);
                    jtbApellido.setEditable(false);
                    jtbNombre.setEditable(false);
                    jtbDomicilio.setEditable(false);
                    jtbTelefono.setEditable(false);
                    jtbCorreo.setEditable(false);
            
        }
                    jlbtnActualizar.setEnabled(false);
                    jlbtnBorrar.setEnabled(true);
                    jlbtnNuevo.setEnabled(true);
                    jlbtnCancelar.setEnabled(false);
                    
            listarPropietarios();
        
    }//GEN-LAST:event_jlbtnActualizarMousePressed

    private void jlbtnBorrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbtnBorrarMousePressed
        // TODO add your handling code here:
        
          
        String id=(jtbCuit.getText());
        
        
        
        if((JOptionPane.showConfirmDialog(null, "Realmente desea Eliminar el Propietario "+id+" ?", "Confirmar Borrado",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE))==0)
        {
           propietarioData.borrarPropietario(id); 
        }
                    jtbCuit.setEditable(false);
                    jtbApellido.setEditable(false);
                    jtbNombre.setEditable(false);
                    jtbDomicilio.setEditable(false);
                    jtbTelefono.setEditable(false);
                    jtbCorreo.setEditable(false);
                    
                    jtbCuit.setText("");
                    jtbApellido.setText("");
                    jtbNombre.setText("");
                    jtbDomicilio.setText("");
                    jtbTelefono.setText("");
                    jtbCorreo.setText("");
                    
        jlbtnBorrar.setEnabled(false);
        
        listarPropietarios();
    }//GEN-LAST:event_jlbtnBorrarMousePressed

    private void jlbtnBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbtnBuscarMousePressed
        // TODO add your handling code here:
        
         String idUser=JOptionPane.showInputDialog ( "Introduzca un CUIT :" );
            
            jtbCuit.setText(idUser);
        
       // int id=Integer.parseInt(jtbCuit.getText());
         
            propietario = propietarioData.buscarPropietario(idUser);
                
                if(propietario!=null){
                    
                    jtbCuit.setText((propietario.getCuitPropietario()));
                    jtbApellido.setText(propietario.getApellidoPropietario());
                    jtbNombre.setText(propietario.getNombrePropietario());
                    jtbDomicilio.setText(propietario.getDomicilioPropietario());
                    jtbTelefono.setText((propietario.getTelefono()));
                    jtbCorreo.setText(propietario.getEmail());
                    
                    jtbCuit.setEditable(true);
                    jtbApellido.setEditable(true);
                    jtbNombre.setEditable(true);
                    jtbDomicilio.setEditable(true);
                    jtbTelefono.setEditable(true);
                    jtbCorreo.setEditable(true);
        
                    
                    jlbtnBorrar.setEnabled(true);
                    jlbtnActualizar.setEnabled(true);
                    jlbtnNuevo.setEnabled(false);
                    jlbtnCancelar.setEnabled(true);
                }
    }//GEN-LAST:event_jlbtnBuscarMousePressed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // TODO add your handling code here:
        MenuPrincipalN.jlblIcon.setVisible(true);
        MenuPrincipalN.jlblProp.setVisible(false);
        MenuPrincipalN.jlblInfo.setText("INFORMACION");
        this.dispose();
    }//GEN-LAST:event_jLabel7MousePressed

    public void listarPropietarios(){
        
        //********** Array to JTable****
        
        DefaultTableModel modeloTabla=new DefaultTableModel();
        
        modeloTabla.addColumn("CUIT");
        modeloTabla.addColumn("Apellido");
        modeloTabla.addColumn("Nombres");
        modeloTabla.addColumn("Domicilio");
        modeloTabla.addColumn("Telefono");
        modeloTabla.addColumn("E-Mail");
        
        //creamos el array
        String[] datoPropietario=new String[6];
        
        for(int i=0;i<propietarioData.listarPropietario().size();i++){
          
           datoPropietario[0]=(propietarioData.listarPropietario().get(i).getCuitPropietario());
           datoPropietario[1]=(propietarioData.listarPropietario().get(i).getApellidoPropietario());
           datoPropietario[2]=(propietarioData.listarPropietario().get(i).getNombrePropietario());
           datoPropietario[3]=(propietarioData.listarPropietario().get(i).getDomicilioPropietario());
           datoPropietario[4]=(propietarioData.listarPropietario().get(i).getTelefono());
           datoPropietario[5]=(propietarioData.listarPropietario().get(i).getEmail());
           
            modeloTabla.addRow(datoPropietario);
        }
        
        jtPropietario.setModel(modeloTabla);
        
        //********** Array to JTable****
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbtnActualizar;
    private javax.swing.JLabel jlbtnBorrar;
    private javax.swing.JLabel jlbtnBuscar;
    private javax.swing.JLabel jlbtnCancelar;
    private javax.swing.JLabel jlbtnGuardar;
    private javax.swing.JLabel jlbtnNuevo;
    private javax.swing.JTable jtPropietario;
    private javax.swing.JTextField jtbApellido;
    private javax.swing.JTextField jtbCorreo;
    private javax.swing.JTextField jtbCuit;
    private javax.swing.JTextField jtbDomicilio;
    private javax.swing.JTextField jtbNombre;
    private javax.swing.JTextField jtbTelefono;
    // End of variables declaration//GEN-END:variables
}
